baseURL: https://Destroyer616.github.io
languageCode: en-us
build:
  writeStats: true
params:
  title: Saikiran Reddy Anugula
  author: Saikiran Reddy Anugula
  description: Website Title
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [Github Pages](https://pages.github.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Anugula Saikiran Reddy"
    tagline: Security Engineer
    location: "Hyderabad, INDIA"
    photo: picture.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/saikiran-reddy-anugula-sixonesix/"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/Destroyer616"
        title: GitHub
      - icon: fab fa-twitter
        url: "https://twitter.com/Anugula10/"
        title: Twitter
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: Im Saikiran Reddy a passionate Cyber security engineer.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Cyber Security Engineer.
        dates: 2021 - *Present*
        company: Suneratech Sutherland
        details: |1-
          - Worked as a vulnerability management analyst.
              - Helped patch number of critical vulnerable systems in the organization.
          - Written scripts to automate some of the processes in the vulnerability management.
          - Worked on power query to automate the process of vulnerability report preparation which con
            be presented in a understandable format to the clients.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Bachelors in Computer Science Engineering.
        college: JBREC
        dates: 2015 - 2019
        percentage: 65
      - degree: Intermediate
        college: Sri Chaitanya Junior College.
        dates: 2013-2015
        percentage: 85
      - degree: SSC
        college: H.S.H.S
        dates: 2015
        percentage: 92
#  publication:
#    title: Publications
#    icon: fas fa-book
#    format:
#      - date
#      - title
#      - authors
#      - journal
#    types:
#      - Journal Articles
#      - Proceedings
#    list:
#      - title: >-
#          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
#          eiusmod tempor incididunt ut labore et dolore magna aliqua.
#        authors: "F Last, F Second, P secondary"
#        date: "2018"
#        journal: "Journal of Field 52 (16), 9033-9044"
#        url: "#"
#        type: Journal Articles
#      - title: >-
#          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
#          eiusmod tempor incididunt ut labore et dolore magna aliqua.
#        authors: "F Last, F Second, P secondary"
#        date: "2018"
#        journal: "Journal of Field 52 (16), 9033-9044"
#        url: "#"
#        type: Journal Articles
#      - title: >-
#          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
#          eiusmod tempor incididunt ut labore et dolore magna aliqua.
#        authors: "F Last, F Second, P secondary"
#        date: "2018"
#        journal: "Journal of Field 52 (16), 9033-9044"
#        url: "#"
#        type: Proceedings
  project:
    title: Projects and Certificates
    icon: fas fa-project-diagram
    list:
      - title: Red Hat Certified System Administrator.
        url: "https://rhtapps.redhat.com/verify?certId=230-122-822"
        description: red hat certified system administarir, linux administration.
      - title: Comptia Security Plus.
        url: "https://www.credly.com/badges/52eaefac-ae53-4e53-9f70-194e8c6d9a9c/public_url"
        description: This certificate validates baseline skills necesary to perform COmputer
                      security functions in security job.
      - title: Microsoft Azure Administrator.
        url: "https://learn.microsoft.com/api/credentials/share/en-us/kiranreddy-3145/68FAA2EF1659E4BC?sharingId=9746CB64FA6C9FFE"
        description: Validate ability to configure, manage, secure, and administer Azure environments.
      - title:  Google Cybersecurity Professional
        url:  "https://coursera.org/share/349f229fe8c4af6ee0b50fe1ea44da87"
        description:  "Those who earn the Google Cybersecurity Certificate have completed eight courses, developed by Google, that include hands-on, practicebased assessments and are designed to prepare them for entry-level oles in cybersecurity. They are competent in beginner-level Python, Linux, SQL, Security Information and Event Management (SIEM) tools, and Intrusion Detection Systems (IDS). They know how to identify common cybersecurity risks, threats, and vulnerabilities, as well as the techniques to mitigate."
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Vulnerability Management"
        skillrating: 90
      - skill: "Linux, Redhat Linux"
        skillrating: 88
      - skill: "Bash Scripting, Python"
        skillrating: 70
      - skill:  "Power query, Tableau"
        skillrating:  60
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Watching Sports
      - hobby: Watching Content.
      - hobby: Distro hopping.
